### ISSUE TITLE
Print on client browser from the server

### ISSUE THREAD

**Issue by jecfarolan360** [charlieuki/receipt-printer#1]
Hello, I would like to ask if it can print on my browser from the server through the internet. My website is deployed on the Windows server. Thanks. I've been struggling on printing the receipts in my browser through the internet.

**Comment by charlieuki** [comment]
Sorry, can you please elaborate your issue?

**Comment by 0l1v3r5** [comment]
> Hello, I would like to ask if it can print on my browser from the server through the internet. My website is deployed on the Windows server. Thanks. I've been struggling on printing the receipts in my browser through the internet.

Did you finally find a solution ?

**Comment by 0l1v3r5** [comment]
I have the same problem and I have been working on it for weeks. I haven't found the solution yet. @charlieuki, in fact, he wants to make printing from the browser with his website hosted on a shared hosting. @jecfarolan360  isn't it ?

**Comment by charlieuki** [comment]
> I have the same problem and I have been working on it for weeks. I haven't found the solution yet. @charlieuki, in fact, he wants to make printing from the browser with his website hosted on a shared hosting. @jecfarolan360 isn't it ?

Basically this package plays the role of **[server]** based on the following scheme:
```
[receipt printer] <---- USB / LAN ----> [server] <---- [client browser]
```

So it's like the client opens a URL in the browser to trigger the server to print the receipt. As simple as that.

**Comment by cntabana** [comment]
Hi , @charlieuki , thank you so much for your hard work. 

I have tried to print from server(online) , however I have got this error message
 **Exception
Failed to print. Command "smbclient '//restaurant/dafka' -c 'print -' -N -m SMB2" failed with exit code 127: sh: 1: smbclient: not found**

Any guide please

**Comment by charlieuki** [comment]
> Hi , @charlieuki , thank you so much for your hard work.
> 
> I have tried to print from server(online) , however I have got this error message
> **Exception Failed to print. Command "smbclient '//restaurant/dafka' -c 'print -' -N -m SMB2" failed with exit code 127: sh: 1: smbclient: not found**
> 
> Any guide please

Hi there @cntabana can you post how your infrastructure is? Is it something similar to:
```
[receipt printer] <---- USB / LAN ----> [server] <---- [client browser]
```
or is it something else? Can you also post the content of your `config/receiptprinter.php` file?

**Comment by adnandogar** [comment]
this package only supports lan/usb based thermal printer, which should be connected to localhost.
@jecfarolan360 in your case it is not possible with this package as your website which is working with window, that machine is not connected with any printer, your localhost computer is connected with printer.

**Comment by charlieuki** [comment]
> this package only supports lan/usb based thermal printer, which should be connected to localhost.
> @jecfarolan360 in your case it is not possible with this package as your website which is working with window, that machine is not connected with any printer, your localhost computer is connected with printer.

Thank you for the clear explanation @adnandogar
