### ISSUE TITLE
Extend the ability to set currency

### ISSUE THREAD

**Issue by MustafaRaarujeed** [charlieuki/receipt-printer#10]
- **Issue**:
Currently, the default currency variable is set to `private $currency = 'Rp';` in the main `ReceiptPrinter` class. And there is no setter method to set the currency to the desired one. This is also included in the `Item` class where the currency is a private variable with no public available method to set the currency `private $currency = 'Rp';`

- **Reason for the change**:
Multiple currencies might be used when printing a receipt. Having a public method that set the currency to the desired one would be helpful. 

- **Updates to include**:
A unified public method in the main class `ReceiptPrinter` to set the currency and to be used alongside the other setters methods such as `Tax`, `Store`, `Logo` .. etc

**Comment by charlieuki** [comment]
Thank you for the updates @MustafaRaarujeed
