### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by Andresan1st** [charlieuki/receipt-printer#20]
I have used this plugin and the results are very good but I don't know how to change the size of the printout?

I have seen the function at the vendor but I can't find any function that changes the font size

**Comment by Andresan1st** [comment]
![Uploading wwwewe.png…]()

**Comment by Andresan1st** [comment]
![wwwewe](https://user-images.githubusercontent.com/32333450/117159171-42d2dd00-adea-11eb-977b-4820b8610066.png)

**Comment by muhammadmarwan** [comment]
Hi can you share your code please.

**Comment by charlieuki** [comment]
> I have used this plugin and the results are very good but I don't know how to change the size of the printout?
> 
> I have seen the function at the vendor but I can't find any function that changes the font size

Hi there! The latest release has the feature to change text size: https://github.com/charlieuki/receipt-printer/releases/tag/1.2.4
