### ISSUE TITLE
copy(\\Hp-PC\Everycom-58): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by meet0929** [charlieuki/receipt-printer#25]
How to check the printer name and set to the printer connector_description. I tried with rename the printer which showing in lits.

Using the Local env in the Windows.

![image](https://user-images.githubusercontent.com/30224694/132640058-872d1e09-761f-483e-99a0-d1214dfada14.png)

**Comment by hamza-saqib** [comment]
how you solved this
