### ISSUE TITLE
Image print

### ISSUE THREAD

**Issue by darkwolf1812** [charlieuki/receipt-printer#26]
How do I print an image??
I need to put a logotype in the top of receipt.

Regards.

**Comment by jumarjuaton** [comment]
@darkwolf1812 @charlieuki didn't add this feature yet when I checked it.

**Comment by charlieuki** [comment]
The function `printLogo()` has been added on [1.2.5a](https://github.com/charlieuki/receipt-printer/releases/tag/1.2.5a), but it still needs testing.
See the [example section](https://github.com/charlieuki/receipt-printer/releases/tag/1.2.5a) about how to use this function.

**Comment by jumarjuaton** [comment]
This is nice @charlieuki ! Does this work when your POS is uploaded on a shared hosting server?

**Comment by charlieuki** [comment]
> This is nice @charlieuki ! Does this work when your POS is uploaded on a shared hosting server?

I have never tested it on a shared hosting server, but it should work as long as:
1. the printer connector settings are configured properly
2. the image path is correct (should be relative to the path on the server)

**Comment by jumarjuaton** [comment]
Awesome!
