### ISSUE TITLE
Problem Logo and QR CODE

### ISSUE THREAD

**Issue by iamphone** [charlieuki/receipt-printer#28]
Hi everyone
I have a problem when I try to print by inserting the logo
I get this error:
File 'http://127.0.0.1:8000/images/logo/1638795775.png' does not exist, or is not readable.
the file is accessible I also made a test with a link to an online image and I have the same problem
Also when I use:
// Set QR code
$printer->setQRcode([
    'tid' => $transaction_id,
]);

instead of qr I print a string in an array and not qr

is there any way even to use the barcode instead?
Thank you so much for all the work done, the rest works perfectly!

**Comment by simsar78** [comment]
Hello,
i have same problem with image/logo .

Another questione: 
it's possible print an html2canvas image on the fly ?


Thanks

**Comment by iamphone** [comment]
To print the image I solved this:
From this
$img = EscposImage::load(asset('storage/2.png), false);
$printer -> bitImage($img);
to this
$img = EscposImage::load(public_path() . '/storage/2.png', false);
$printer -> bitImage($img);
