### ISSUE TITLE
the library is deferred on laravel version 8.

### ISSUE THREAD

**Issue by barenpasaribu** [charlieuki/receipt-printer#31]
can you update this library so that it can be used in laravel version 8.

Thanks before..

**Comment by charlieuki** [comment]
I am currently working to update this package to Laravel 8 and 9, so expect an update soon.

**Comment by charlieuki** [comment]
> can you update this library so that it can be used in laravel version 8.
> 
> Thanks before..

Just tested with Laravel 8.83.26 and Laravel 9.43.0 without any issues.
