### ISSUE TITLE
Inconsistant receipt printing output

### ISSUE THREAD

**Issue by Rana-xD** [charlieuki/receipt-printer#44]
I have an issue when sometime it print correctly and something it is not. And I don't know what is the issue. Below is my custom code 

`   
      
    
            public function printXscometicReceipt(){
        if ($this->printer) {
            // Get request amount
            $seller = $this->getPrintableHeader(
                'Seller: ',
                'Admin'
            );
            $date = $this->getPrintableHeader(
                'Date: ',
                date('d-m-Y / h:i A'),
            );
            $product_header = ['Name', 'Price', 'Qty', 'Total'];
            // Init printer settings
            $this->printer->initialize();
            // Print receipt headers
            $this->printer->setJustification(Printer::JUSTIFY_CENTER);
            // Print logo
            // $this->printLogo();
            $this->printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
            $this->printer->feed();
            $this->printer->text("{$this->store->getName()}\n");
            $this->printer->feed(2);
            $this->printer->selectPrintMode();
            // $this->printer->setJustification(Printer::JUSTIFY_LEFT);
            $this->printer->text($seller . "\n");
            $this->printer->feed();
            $this->printer->text($date . "\n");
            $this->printer->feed(2);    

            $this->printDashedLine();
            $this->printer->setEmphasis(true);
            
            $this->printer->text($this->getReceiptHeader());
            
            $this->printer->setEmphasis(false);
            $this->printer->feed(2);
            // $this->printDashedLine();
            
            foreach ($this->items as $item) {
                $this->printer->text($item."\n");
            }
            $this->printer->feed();
            $this->printDashedLine();
                
            
           
            // Cut the receipt
            $this->printer->cut();
            $this->printer->close();
        } else {
            throw new Exception('Printer has not been initialized.');
        }
    }`

You can check the image attachment. 

![IMG_6785](https://github.com/charlieuki/receipt-printer/assets/18557407/9966650d-7747-449f-9b69-1ceb57cabe7f)

As you can see in the image. It print different output even though I use the same code. ( The wrong one is missing top part ).

@charlieuki  

If you could provide any tips to fix this, it will be helpful for me.
Thank you.

**Comment by charlieuki** [comment]
@Rana-xD There might be issue with the printer when specifying the following:
```
...
$this->printer->selectPrintMode();
...
```
Can try to set it to a specific mode like:
```
$this->printer->selectPrintMode(Printer::MODE_FONT_A);
```
Available options:
```
MODE_FONT_A
MODE_FONT_B
MODE_EMPHASIZED
MODE_DOUBLE_HEIGHT
MODE_DOUBLE_WIDTH
MODE_UNDERLINE
```
Hopefully it helps!

**Comment by Rana-xD** [comment]
@charlieuki 

Thank you for your help. It works now. 

And I have another issue regarding input another language character beside English. When I try to put it, it will print **?**. 

Here is the sample code

`$total_riel = $this->getPrintableHeader(
                'Total      (KHR):',
                $this->total_riel.' ៛',
            );`

And here is the result 

![IMG_6791](https://github.com/charlieuki/receipt-printer/assets/18557407/13fc4a85-b5fc-4456-8db6-514327d7226f)

My Thermal Printer Model is **Rongta RP80USE**.
